### ISSUE TITLE
Скласти інтро

### ISSUE THREAD

**Issue by Vankert353** [Vankert353/homepage#5]
Скласти інтро (вступ), де в 2-4 реченнях описати, що замовник робить, що подобається робити, що хочеться робити краще, що важливо робити, тощо.

**Comment by 89elizabeth** [comment]
GENGHIS KHAN
Great conqueror
— Hey! I am a great conqueror. More than 60 years of experience in conquering states. Organization of teams for large projects, reforms within finished projects, creat team without the involvement of HR.
