### ISSUE TITLE
Скласти таймлайн

### ISSUE THREAD

**Issue by Vankert353** [Vankert353/homepage#7]
Скласти список всіх (важливих) життєвих подій, визначних дат, досягнень, періодів, що дали приємний і неприємний досвід, тощо. В цьому конкретному випадку довгих списків не буває, натомість бувають погано згорнуті, тому пакуємо сюди все підряд, а про "лишні" події можна буде промовчати пізніше. Список повинен бути систематизованим і посортованим в такий спосіб, щоб читач швидко зрозумів "паттерн" і міг легко орієнтуватись в просторі і часі цього резюме.

**Comment by 89elizabeth** [comment]
1184 year

captivity of Temujin's wife by the Merkits

1185 year

birth of Temujin's second son

1186 year

birth of Temujin's third son

1190 year

birth of the fourth son of Genghis Khan

1196 year

the combined forces of Temujin, Tooril Khan and the Jin troops attack the Tatar tribe

1199 year

victory of the combined forces of Temujin, Wan Khan and Jamukha over the Naiman tribe led by Buyuruk Khan

1200 year

victory of the joint forces of Temujin and Wang Khan over the Taichiut tribe

1203 year

victory over kereites

1205 year

betrayal and surrender of Jamuqa by his nukers to Temujin; execution of Jamuqa

1207 year

Genghis Khan's attacks on the Tangut state of Xi Xia

1215 year

fall of Beijing
