### ISSUE TITLE
Скласти додаткові інформаційні блоки

### ISSUE THREAD

**Issue by Vankert353** [Vankert353/homepage#8]
Можна зробити резюме менш формальним, додавши додаткові блоки, які містять корисну інформацію, але подають її в "розважальній" формі. Наприклад, що подобається і не подобається, сильні і слабкі сторони, перелік навиків чи хобі, інфографіка або ж інтерактивні модулі, тощо. Варто написати контент такого блоку раніше, ніж починати верстку, бо його розміри впливатимуть на розміщення елементів на сторінці.

**Comment by 89elizabeth** [comment]
LANGUAGES
Монгольский

SKILLS
CONQUEST REFORMS EXECUTION REPRODUCTION MANAGING BIG TEAMS

CHARACTER
EXPLORER STRAIGHTFORWARD DEVOTED PEDANTIC AGNOSTIC CONTENTIOUS PROCRASTINATOR RELEVANT EMPATHETIC STORYTELLER CONFIDENT CONSISTENT CHALLENGING

LIKES😃
GOLD POWER HORDE

DISLIKES😞
SILVER LOSE DIE

WANTS🥺
CONQUER THE WHOLE WORLD TO READ MORE TO BE MORE BRAVE TO BECOME A SUPERKING

EDUCATION
Every day
"How to be great"
